### ISSUE TITLE
Linux sudo authentication step isn't recognizing SSH key method

### ISSUE THREAD

**Issue by juluriaj** [awslabs/cloud-migration-factory-on-aws#2]
Running the step to install CloudEndure agent on servers using command "python 1-CEAgentInstall.py --Waveid 1"

At the following step, when user enters capital Y instead of small Y, its not recognizing SSH key based authentication, instead it is trying password based. 

At line # 312, _has_key should check for both Y and y.  

                status = linuxpkg.install_cloud_endure(server['server_fqdn'], user_name,
                                                     pass_key,
                                              **_has_key in 'y'_**, project['InstallToken'])

Error Log: 
-----------

******************************************
* Enter Linux Sudo username and password *
******************************************
Linux Username: ec2-user
If you use a private key to login, press [Y] or if use password press [N]: y
Private Key file name: cedr.pem
--------------------------------------------------------
- Installing CloudEndure for:  ec2-xxxxx.compute-1.amazonaws.com -
--------------------------------------------------------
Unable to connect to host ec2-xxxx.compute-1.amazonaws.com with username ec2-user due to Bad authentication type; allowed types: ['publickey', 'gssapi-keyex', 'gssapi-with-mic']

**Comment by wallylv** [comment]
resolved in the new release
